Improve user experience

diff --git a/resources/tools/scripts/install b/resources/tools/scripts/install
--- a/resources/tools/scripts/install
+++ b/resources/tools/scripts/install
@@ -21,19 +21,26 @@ else
     CURRENT_PATH="$(dirname "$(readlink -f "$0")")"
 fi
 
-if [ -f "$CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar" ]; then
-      echo "ballerina-command-${ballerina.command.version}.jar is already exists hence update failed."
-      exit 1
+\cp $CURRENT_PATH/ballerina-command-${ballerina.command.version}/lib/ballerina-command-${ballerina.command.version}.jar $CURRENT_PATH/../lib
+
+if [ $? -ne '0' ]; then
+  echo "error occurred while copying ballerina jar"
+  # remove if copied with an error.
+  if [ -f "$CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar" ]; then
+        rm -rf $CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar
+  fi
+  exit $?
 fi
 
-\cp $CURRENT_PATH/ballerina-command-${ballerina.command.version}/lib/ballerina-command-${ballerina.command.version}.jar $CURRENT_PATH/../lib || { echo 'copy tool jar failed.' ; exit 1; }
 \cp $CURRENT_PATH/ballerina-command-${ballerina.command.version}/bin/ballerina $CURRENT_PATH/../bin
 
 if [ $? -ne '0' ]; then
-  echo "copy ballerina file failed."
+  echo "error occurred while copying ballerina file."
   # remove already copied jar.
-  rm -rf $CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar
-  exit 1
+  if [ -f "$CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar" ]; then
+        rm -rf $CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar
+  fi
+  exit $?
 fi
 
 echo "Updated to latest command version: ${ballerina.command.version}"
