Make ballerina update atomic

diff --git a/resources/tools/bin/ballerina b/resources/tools/bin/ballerina
--- a/resources/tools/bin/ballerina
+++ b/resources/tools/bin/ballerina
@@ -31,7 +31,14 @@ then
 
     if [ -d "$CURRENT_PATH/../ballerina-command-tmp" ]; then
         $CURRENT_PATH/../ballerina-command-tmp/install
+        if [ $? -ne '0' ]; then
+          echo "Command updated successfully failed"
+          rm -rf $CURRENT_PATH/../ballerina-command-tmp
+          exit 1
+        fi
         rm -rf $CURRENT_PATH/../ballerina-command-tmp
+        echo "Command updated successfully"
+        exit 0
     fi
 else
     BALLERINA_VERSION=`cat $CURRENT_PATH/../distributions/ballerina-version`
diff --git a/resources/tools/scripts/install b/resources/tools/scripts/install
--- a/resources/tools/scripts/install
+++ b/resources/tools/scripts/install
@@ -21,8 +21,24 @@ else
     CURRENT_PATH="$(dirname "$(readlink -f "$0")")"
 fi
 
-\cp $CURRENT_PATH/ballerina-command-${ballerina.command.version}/lib/ballerina-command-${ballerina.command.version}.jar $CURRENT_PATH/../lib
+if [ -f "$CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar" ]; then
+      echo "ballerina-command-${ballerina.command.version}.jar is already exists hence update failed."
+      exit 1
+fi
+
+\cp $CURRENT_PATH/ballerina-command-${ballerina.command.version}/lib/ballerina-command-${ballerina.command.version}.jar $CURRENT_PATH/../lib || { echo 'copy tool jar failed.' ; exit 1; }
 \cp $CURRENT_PATH/ballerina-command-${ballerina.command.version}/bin/ballerina $CURRENT_PATH/../bin
+
+if [ $? -ne '0' ]; then
+  echo "copy ballerina file failed."
+  # remove already copied jar.
+  rm -rf $CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar
+  exit 1
+fi
+
+echo "Updated to latest command version: ${ballerina.command.version}"
+echo "Cleaning old files..."
+
 for file in $CURRENT_PATH/../lib/*; do
     if [ -f "$file" ] && [[ "$file" == *ballerina-command*.jar ]] && [[ "$file" != *ballerina-command-${ballerina.command.version}.jar ]]; then
 	rm -rf $file
