Modify ballerina scripts to point to INSTALL.txt

diff --git a/resources/tools/bin/ballerina b/resources/tools/bin/ballerina
--- a/resources/tools/bin/ballerina
+++ b/resources/tools/bin/ballerina
@@ -26,7 +26,11 @@ then
     JAVA_COMMAND=java
     if test -d "$CURRENT_PATH/../dependencies/jdk8u202-b08-jre"; then
       JAVA_COMMAND="$CURRENT_PATH/../dependencies/jdk8u202-b08-jre/bin/java"
+    elif [[ `$JAVA_COMMAND -version 2>&1 | grep -e "1.8."` = "" ]]; then
+      echo "Compatible JRE 8 not found. Please follow the instructions in $(cd $CURRENT_PATH/../; pwd)/INSTALL.txt to install and setup Ballerina."
+      exit 1;
     fi
+
     $JAVA_COMMAND -jar $CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar "$@"
 
     if [ -d "$CURRENT_PATH/../ballerina-command-tmp" ]; then
@@ -62,6 +66,9 @@ then
     JAVA_COMMAND=java
     if test -d "$CURRENT_PATH/../dependencies/jdk8u202-b08-jre"; then
       JAVA_COMMAND="$CURRENT_PATH/../dependencies/jdk8u202-b08-jre/bin/java"
+    elif [[ `$JAVA_COMMAND -version 2>&1 | grep -e "1.8."` = "" ]]; then
+      echo "Compatible JRE 8 not found. Please follow the instructions in $(cd $CURRENT_PATH/../; pwd)/INSTALL.txt to install and setup Ballerina."
+      exit 1;
     fi
     $JAVA_COMMAND -jar $CURRENT_PATH/../lib/ballerina-command-${ballerina.command.version}.jar "$@"
 fi
